### ISSUE TITLE
Carret is always put at the end of text after transforming block using slash syntax

### ISSUE THREAD

**Issue by PJerkovic** [Dashibase/lotion#29]
To reproduce:
1. Convert block to any other type of content block using slash syntax
2. Caret will be put at the end of text even if slash was somewhere in the middle

Probably the reason for this:
`Lotion.vue::setBlockType()` calls `moveToEnd()` even if transformation was invoked with slash syntax. There is a call before that in `Block.vue::clearSearch()` to set carret at right position.

**Comment by vvidday** [comment]
Related issue - transforming block using slash syntax that triggers `clearSearch` removes the last few characters.
<details>
  <summary>Example</summary>

![slashend-before](https://user-images.githubusercontent.com/45852430/182341367-0d7c8f07-aaf8-44de-a429-8b990d7fd066.gif)

</details>

Seemed like an issue with `Block.vue::getCaretPos` not getting the correct selection on mouse clicks - the logic is already there (using 'enter' to transform the blocks works correctly), but fails on mouse clicks specifically.

Source of the bug seems to be from `vue-draggable` package, where mouse clicks on any element inside the draggable object would result in `window.getSelection()` returning a null selection instead of the actual value. Demo [here](https://playcode.io/934508).

Moving the `handle` class from the entire `BlockMenu` component to just the div containing the menu icon seems to fix the issue.

**Comment by greentfrapp** [comment]
Fixed by #33 thanks @PJerkovic for reporting this and thanks @vvidday for the fix! 🧴
